### ISSUE TITLE
Issue getting a List

### ISSUE THREAD

**Issue by m4tta** [kylelemons/go-gypsy#12]
Ok, I've beat my head against the wall with this yaml thing all night. I have this yaml here.

``` yaml
bot:
  server: irc.rizon.net
  port: 6667
  nick: botname
  identpass: somepass
  password: anotherpass
  channels:
        - #channel1
        - #channel2
        - #channel3
```

I am trying to get a list of channels I can iterate through, but I can't manage to get the yaml parser to return a list I can only access single elements.
