### ISSUE TITLE
how to parse appengine app.yaml file

### ISSUE THREAD

**Issue by vtolstov** [kylelemons/go-gypsy#7]
Hello. I'm try to parse app.yaml appengine like file with this package and stopped at getting type List, for example i have this file

```
application: xxxx
version: 1
runtime: go
api_version: go1

handlers:
 - url: /static
   static_dir: static/
   upload: static/
 - url: /.*
   script: _go_app
```

How can i get handlers to iterate in for cycle?
